name: Test out local action
on:
  schedule:
    - cron: '15 23 * * *'  # Run every day at 11:15 PM

jobs:
  make-prediction:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c  # v3.3.0
      - name: Set up Python
        uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435  # v4.5.0, will make use of `.python-version`
      - name: Install dependencies
        run: |
          make install
      - name: Hello world action step
        uses: ./.github/actions/refresh_enphase_tokens
        id: refresh_enphase_tokens
