name: Test out local action
on: push

jobs:
  make-prediction:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c  # v3.3.0
      - name: Hello world action step
        uses: ./.github/actions/refresh_enphase_tokens
        id: refresh_enphase_tokens
